name: Lint
on: [push]
permissions:
  contents: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
